import { ApolloServer, gql } from 'apollo-server';

const server = new ApolloServer({
  typeDefs: gql`
    type Query {
      user: User
    }

    type User {
      id: ID!
      userName: String!
    }
  `,

  resolvers: {
    Query: {
      user: () => {
        return {
          id: 'baisiblndqwod',
          userName: () => 'Guto',
        };
      },
    },
  },
});
server.listen(4000).then(({ url }) => {
  console.log(`Server Listening on url ${url}`);
});
